In [4]:
import numpy as np
from numpy.random import randn

In [19]:
data = randn(2, 3)
data

array([[-0.57307484, -0.94468651,  0.19438995],
       [ 0.51129456,  1.44620142,  0.15042952]])

In [23]:
# array 연산

In [20]:
data + [[1,2,3]]

array([[0.42692516, 1.05531349, 3.19438995],
       [1.51129456, 3.44620142, 3.15042952]])

In [21]:
data * 10

array([[-5.73074844, -9.44686506,  1.94389946],
       [ 5.11294555, 14.46201415,  1.5042952 ]])

In [22]:
data + data

array([[-1.14614969, -1.88937301,  0.38877989],
       [ 1.02258911,  2.89240283,  0.30085904]])

In [27]:
# data shape

In [28]:
data.shape

(2, 3)

In [30]:
data.size

6

In [31]:
data.dtype

dtype('float64')

In [ ]:
# numpy의 명령어중 shape와 size의 차이점을 설명하시오.
shape 행렬의 크기
size 요소의 갯수 (컴퓨터에 할당되는 저장 공간 개수)

In [ ]:
# array의 색인 

In [32]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr[1][:2]

array([4, 5])

In [34]:
arr[1][1:3]

array([5, 6])

In [35]:
arr[0][1:3]

array([2, 3])

In [36]:
arr[0]

array([1, 2, 3])

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr[1]

array([4, 5, 6])

In [40]:
arr[1:2]

array([[4, 5, 6]])

In [41]:
arr[1, :2]

array([4, 5])

In [42]:
arr[0, [0,1]]

array([1, 2])

In [43]:
arr[0, 1]

2

In [46]:
arr[0][0:2]


array([1, 2])

In [47]:
arr[[0,1], [0,1]]

array([1, 5])

In [59]:
arr[[0,1],[0,1]]
# arr(2,3)

array([1, 5])

In [ ]:
arr[0,3][3]

In [ ]:
# shape의 변경 -view

In [5]:
ar = np.array([
    [1,2,3,4],
    [3,4,5,6]
])

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [63]:
ar2 = ar.reshape((4,2))
ar2

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

In [64]:
ar2[0,0] = 10
ar2

array([[10,  2],
       [ 3,  4],
       [ 3,  4],
       [ 5,  6]])

In [ ]:
# dtype의 변경 - new object
dtype의 자료형을 바꿔주는 것.

In [6]:
ar3 = ar.astype(np.float)
ar3

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.]])

In [67]:
np.array?


In [70]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [72]:
data2 = [[1,2,3,4], [4,5,3]]
arr2 = np.array(data2)
arr2
# 타입이 오브젝트로 바뀌면서 오류가 뜨지 않는다.

array([list([1, 2, 3, 4]), list([4, 5, 3])], dtype=object)

In [73]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.array() : 입력데이터를 ndarray로 변환
np.asarray() : 입력데이터를 ndarray로 변환
np.arange() : 내장 range함수와 유사하지만, 리스대신 array로 반환
np.ones() : 주어진 데이터타입과 shape를 가지느 배열 생성 ( 성분 모두 1로 초기화 )
np.ones_like() : 주어진 배열과 동일한 shape과 dtype를 갖는 배열을 생성. 1로 초기화
    > 이미 있는 배열의 서식을 카피함.
np.zero() : ones와 같지만 0으로 초기화
np.empty() : 메모리를 할당하지만 초기화가 없음
eye(n, m, k=0) : N x M 대각행렬 생성. k에 따라 대각이 이동
np.identity() : 단위행렬 생성
    

In [76]:
a = np.array(data1)

In [15]:
np.zero_like(ar)

AttributeError: module 'numpy' has no attribute 'zero_like'

In [77]:
np.asarray(a)

array([6. , 7.5, 8. , 0. , 1. ])

In [78]:
np.array(a)

array([6. , 7.5, 8. , 0. , 1. ])

In [91]:
np.ones((2,3),int,0)

array([[1, 1, 1],
       [1, 1, 1]])

In [93]:
np.ones_like(a)

array([1., 1., 1., 1., 1.])

In [96]:
np.eye(2,3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [97]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# dtype을 변경하려면 astype() 함수를 사용한다. 

In [98]:
arr2 = np.array([
    [3,4,5],
    [4,5,2]
])

In [99]:
arr2.dtype

dtype('int32')

In [100]:
arr2.astype(float)

array([[3., 4., 5.],
       [4., 5., 2.]])

In [ ]:
# float dtype를 int로 바꾸는것은 기피하자. 소숫점 아래는 버림으로 되기때문! 
다른 방법인 np.trunc(arr)을 사용! 소숫점 아래부분은 올림처리함.

In [103]:
a22 = randn(3,3)
a22

array([[-0.18997316, -0.2442019 ,  0.47192515],
       [-0.66521994, -1.46976846, -0.64032928],
       [-0.36053506,  0.95521732,  1.09795601]])

In [104]:
a22.astype(int)

array([[ 0,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [105]:
np.trunc(a22)
# 정수부분과, 부호를 가져왔네.

array([[-0., -0.,  0.],
       [-0., -1., -0.],
       [-0.,  0.,  1.]])

In [106]:
np.floor(a22)
# 올림

array([[-1., -1.,  0.],
       [-1., -2., -1.],
       [-1.,  0.,  1.]])

In [107]:
np.ceil(a22)
# 소수 첫번째 값에서 올림한 값

array([[-0., -0.,  1.],
       [-0., -1., -0.],
       [-0.,  1.,  2.]])

In [108]:
np.rint(a22)
# 올림

array([[-0., -0.,  0.],
       [-1., -1., -1.],
       [-0.,  1.,  1.]])

In [ ]:
# array의 dtype을 변경할때, 쓰는 함수는 astpye() 이다. 
이때 float타입을 int형으로 바꾸는 것은 바람직하지 않는 이유를 설명하시오. 

float형에서 int형으로 바꾸면 소수점 아래 데이터는 그냥 버려진다. 데이터 왜곡의 위험이 있기 때문에
반올림, 올림을 사용하는 다른 함수를 이용한다. np.floor, np.ceil, np.rint

In [112]:
%matplotlib inline
from __future__ import division

SyntaxError: from __future__ imports must occur at the beginning of the file (<ipython-input-112-57d7d0f42c0f>, line 5)

In [114]:
ndarray에는 서로의 크기가 맞지않아도 연산처리르 도와주는 기능이 있다. 
다음과 같은 그림의 기능의 이름은 무엇인가? 
브로드캐스트

'[]'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [ ]:
array에 대한 설명으로 옳지 않은 것은 무엇인가? 
1. shape의 크기가 맞지 않아도 연산이 가능하다.
2. size는 요소의 갯수와 같다. 
3. ones_like는 주어진 dtype과 shape을 가지는 배열을 생성하며 모든 성분을 1로 초기화한다.
4. identity는 대각행렬만을 생성하는 함수이다. 
5. empty함수는 초기화가 없으나 메모리를 할당한다.

정답 4번



In [115]:
arr1 = np.array([[1., 2., 3., 4.], [5., 6., 7., 8.]])
arr2 = np.array([1., 2.]) 
arr1 + arr2
# 다음과 같은 오류가 뜨는 이유는 무엇인가?

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [116]:
arr3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]]
    ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [117]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])