In [1]:
# numpy import
import numpy as np

In [2]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [3]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [6]:
#numpy를 이용하여 array 정의하기 
# 위에서 만든 파이썬 리스트 이용!
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [7]:
# array의 형태(크기)를 확인 할 수있다..
arr1.shape

(5,)

In [8]:
# 2. 바로 python list를 넣어 줌으로써 만들기
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [9]:
arr2.shape

(5,)

In [10]:
# array의 자료형을 확인 할 수 있다.
arr2.dtype

dtype('int32')

In [13]:
data2

[1, 2, 3, 3.5, 4]

In [12]:
arr3 = np.array(data2)
arr3
# 하나라도 소수점이 생기면 모두 소수점 생김. (자료형 바뀜)

array([1. , 2. , 3. , 3.5, 4. ])

In [15]:
arr3.shape

(5,)

In [14]:
arr3.dtype

dtype('float64')

In [16]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr4.shape
# 4x3의 크기를 갖고 있구나! 2차원 데이터구나!

(4, 3)

### numpy shape 

넘파이에서 해당 array의 크기를 알 수 있다. 
shap를 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인 할 수 있다. 
위에서 arr1.shape의 결과는 (5,)으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다. 
arr4.shape의 결과는 (4,3)으로써, 2차원의 데이터이며 4*3크기를 갖고 있는 array이다.


### numpy 자료형
- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_

### 넘파이의 함수들
1. np.zeros(), np.ones(), np.arange() 함수

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#np.zeros() 함수는 인자로 받는 크기 만큼, 모든요소가 0인 array를 만든다.

In [22]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# np.ones()는 zeros랑 비슷한데 모든 요소를 1로 만든다.

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [28]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때, 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

### 3. array 연산
기본적으로 numpy에서 연선을 할때는 크기가 서로 동일한 array끼리 연산이 진행.
이때 같은 위치에 ㅣㅆ는 요소들끼리 연산이 진행된다.


In [32]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr1.shape

(2, 3)

In [34]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [35]:
arr2.shape

(2, 3)

In [36]:
# 덧셈
arr1 + arr2
# 각 요소끼리 더해진다.

array([[11, 13, 15],
       [17, 19, 21]])

In [37]:
# 뺄셈
arr1 - arr2
# 각 요소끼리 빼진다.

array([[-9, -9, -9],
       [-9, -9, -9]])

In [38]:
#array의 곱셈
# 행렬처럼 곱셈이 진행되는것이 아니라, 각 요소별로 곱셈 진행.
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [39]:
# 나눗셈
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

### 브로드 캐스트!
array는 같은 크기를 가져야 연산이 가능했지만, 
넘파이 이녀석은 브로드캐스트라는 기능을 통해 서로 다른 array끼리 연산 가능하게 해준다.

In [41]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr1.shape

(2, 3)

In [43]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [44]:
arr3.shape

(3,)

In [45]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [46]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [47]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [48]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

### 4. Array 인덱싱
넘파이에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.
이때, 파이썬에서 처럼 1번쨰로 시작하는 것이 아니라 0번째에서 시작하는 것에 주의

In [56]:
arr1 = np.arange(10)
print(arr1)
print(arr1[0])
print(arr1[3])
print(arr1[3:9])
print(arr1[:])

[0 1 2 3 4 5 6 7 8 9]
0
3
[3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]


In [57]:
# 1차원 말고도 그 이상의 차원에서도 가능!

In [64]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr2)
print(arr2[0,0])
print(arr2[2,:])
print(arr2[2,3])
print(arr2[:,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[ 9 10 11 12]
12
[ 4  8 12]


### 5. array boolen 인덱싱 (마스크)
위에서 이용한 다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.

해당 기능은 주로 마스크라고 이야기하는데, boolean인덱싱을 통해 만들어낸 array를 통해

우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.

즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.

In [66]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [67]:
names.shape

(8,)

In [68]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안
# 정규 분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.

data = np.random.randn(8,4)
data

array([[ 0.30864839, -0.11821987, -1.72535241, -1.56410306],
       [-0.28536557,  1.0104964 ,  0.11590485, -0.36272533],
       [-0.83919857,  0.39355853,  0.66845923,  0.21351644],
       [-0.05967676,  0.20147358,  1.53886673,  0.05630489],
       [-0.01740681, -0.67234408, -1.22748374,  0.01552104],
       [-1.16020715, -0.4048893 , -0.66801814,  1.09919979],
       [ 1.5008642 ,  2.78745327, -0.65589422,  0.50933514],
       [-0.14077055,  0.3565112 ,  0.7910861 , -0.89890242]])

In [69]:
data.shape

(8, 4)

위와 같은 names와 data라는 array가 있다.

이때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자.

그리고 이 때, names가 Beomwoo인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용한다.


In [73]:
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [74]:
data[names_Beomwoo_mask, :]

array([[ 0.30864839, -0.11821987, -1.72535241, -1.56410306],
       [-0.28536557,  1.0104964 ,  0.11590485, -0.36272533],
       [-1.16020715, -0.4048893 , -0.66801814,  1.09919979],
       [-0.14077055,  0.3565112 ,  0.7910861 , -0.89890242]])

위의 결과를 보면, 요소가 Beomwoo인 것은 0번째, 1번째, 5번째, 7번째 이므로

data에서 0,1,5,7행의 모든 요소를 꺼내와야 한다.

이를 위해 요소가 Beomwoo인 것에 대한 boolean 값을 가지는 mask를 만들었고

마스크를 인덱싱에 응용하여 data의 0,1,5,7행을 꺼냈다.

**각 행중 True인 값에 해당하는 행만 가져옴.**

In [77]:
# 요소가 kim인 행의 데이터만 꺼내기
data[names == 'Kim', :]

array([[-0.83919857,  0.39355853,  0.66845923,  0.21351644]])

In [79]:
data[(names == 'Kim') | (names == 'Park'), :]

array([[-0.83919857,  0.39355853,  0.66845923,  0.21351644],
       [ 1.5008642 ,  2.78745327, -0.65589422,  0.50933514]])

물론 data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하다.

data array에서 0번째 열의 값이 0보다 작은 행을 구해보자.


In [81]:
# 1. 마스크를 만든다.
# 2. data array에서 0번째 열이 0보다 작은 요소의 boolen 값은 다음과 같다.
data

array([[ 0.30864839, -0.11821987, -1.72535241, -1.56410306],
       [-0.28536557,  1.0104964 ,  0.11590485, -0.36272533],
       [-0.83919857,  0.39355853,  0.66845923,  0.21351644],
       [-0.05967676,  0.20147358,  1.53886673,  0.05630489],
       [-0.01740681, -0.67234408, -1.22748374,  0.01552104],
       [-1.16020715, -0.4048893 , -0.66801814,  1.09919979],
       [ 1.5008642 ,  2.78745327, -0.65589422,  0.50933514],
       [-0.14077055,  0.3565112 ,  0.7910861 , -0.89890242]])

In [82]:
data[:, 0] < 0

array([False,  True,  True,  True,  True,  True, False,  True])

In [83]:
# 위에서 만든 마스크를 이용하여, 0번째 열의 값이 0보다 작은 행을 구한다. 
data[data[:, 0]<0, :]

array([[-0.28536557,  1.0104964 ,  0.11590485, -0.36272533],
       [-0.83919857,  0.39355853,  0.66845923,  0.21351644],
       [-0.05967676,  0.20147358,  1.53886673,  0.05630489],
       [-0.01740681, -0.67234408, -1.22748374,  0.01552104],
       [-1.16020715, -0.4048893 , -0.66801814,  1.09919979],
       [-0.14077055,  0.3565112 ,  0.7910861 , -0.89890242]])

In [84]:
# 이를 통해서 특정 위치에만 우리가 원하는 값을 대입할 수있다.
# 위에서 얻은, 0번째 열의 값이 0보다 작은 행의 2,3번째 열값에 0에 대입해보자.

In [ ]:
array[행, 열요소들]

In [85]:
data

array([[ 0.30864839, -0.11821987, -1.72535241, -1.56410306],
       [-0.28536557,  1.0104964 ,  0.11590485, -0.36272533],
       [-0.83919857,  0.39355853,  0.66845923,  0.21351644],
       [-0.05967676,  0.20147358,  1.53886673,  0.05630489],
       [-0.01740681, -0.67234408, -1.22748374,  0.01552104],
       [-1.16020715, -0.4048893 , -0.66801814,  1.09919979],
       [ 1.5008642 ,  2.78745327, -0.65589422,  0.50933514],
       [-0.14077055,  0.3565112 ,  0.7910861 , -0.89890242]])

In [87]:
data[:,0]

array([ 0.30864839, -0.28536557, -0.83919857, -0.05967676, -0.01740681,
       -1.16020715,  1.5008642 , -0.14077055])

In [89]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열 값
data[data[:,0]<0, 2:4] = 0
data

array([[ 0.30864839, -0.11821987, -1.72535241, -1.56410306],
       [-0.28536557,  1.0104964 ,  0.        ,  0.        ],
       [-0.83919857,  0.39355853,  0.        ,  0.        ],
       [-0.05967676,  0.20147358,  0.        ,  0.        ],
       [-0.01740681, -0.67234408,  0.        ,  0.        ],
       [-1.16020715, -0.4048893 ,  0.        ,  0.        ],
       [ 1.5008642 ,  2.78745327, -0.65589422,  0.50933514],
       [-0.14077055,  0.3565112 ,  0.        ,  0.        ]])

### 6. Numpy함수 
넘파이에서는 array에 적용되는 다양한 함수가 있다.

#### 1. 하나의 array에 적용되는 함수

In [92]:

arr1 = np.random.randn(5,3)
arr1

array([[ 1.28525402,  0.01184574,  0.61087353],
       [ 0.3781803 ,  2.85173342, -0.36955867],
       [ 0.25414981, -0.4997493 ,  1.84034079],
       [ 1.77259613, -1.7837069 , -0.33948728],
       [ 0.4625316 , -0.46913358,  0.11382239]])

In [93]:
#각 성분의 절댓값으로 변환
np.abs(arr1)

array([[1.28525402, 0.01184574, 0.61087353],
       [0.3781803 , 2.85173342, 0.36955867],
       [0.25414981, 0.4997493 , 1.84034079],
       [1.77259613, 1.7837069 , 0.33948728],
       [0.4625316 , 0.46913358, 0.11382239]])

In [94]:
#각 성분의 제곱근 으로 변환 ( == array ** 0.5) 루트!
np.sqrt(arr1)

C:\Users\ai9198\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[1.13369044, 0.10883812, 0.78158399],
       [0.61496366, 1.68870762,        nan],
       [0.50413273,        nan, 1.35659161],
       [1.3313888 ,        nan,        nan],
       [0.68009675,        nan, 0.33737574]])

In [95]:
# 각 성분의 제곱으로 변환
np.square(arr1)

array([[1.65187790e+00, 1.40321487e-04, 3.73166471e-01],
       [1.43020341e-01, 8.13238351e+00, 1.36573612e-01],
       [6.45921251e-02, 2.49749360e-01, 3.38685421e+00],
       [3.14209705e+00, 3.18161031e+00, 1.15251611e-01],
       [2.13935477e-01, 2.20086315e-01, 1.29555362e-02]])

In [96]:
#각 성분을 무리수 e의 지수로 삼은 값으로 변환
np.exp(arr1)

array([[ 3.61558628,  1.01191618,  1.84203978],
       [ 1.45962609, 17.31777485,  0.69103924],
       [ 1.28936495,  0.60668274,  6.29868439],
       [ 5.88611467,  0.16801418,  0.71213536],
       [ 1.5880893 ,  0.62554402,  1.12055308]])

In [97]:
# 각 성분의 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기
np.log(arr1)

C:\Users\ai9198\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


array([[ 0.25095638, -4.43578722, -0.49286533],
       [-0.97238421,  1.04792703,         nan],
       [-1.36983139,         nan,  0.60995076],
       [ 0.57244521,         nan,         nan],
       [-0.77104041,         nan, -2.17311604]])

In [98]:
np.log10(arr1)

C:\Users\ai9198\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([[ 0.10898897, -1.92643791, -0.21404869],
       [-0.4223011 ,  0.45510893,         nan],
       [-0.59491021,         nan,  0.26489825],
       [ 0.2486098 ,         nan,         nan],
       [-0.3348586 ,         nan, -0.9437723 ]])

In [100]:
np.log2(arr1)

C:\Users\ai9198\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([[ 0.36205353, -6.39948822, -0.71105436],
       [-1.40285387,  1.51183913,         nan],
       [-1.97624895,         nan,  0.87997294],
       [ 0.82586387,         nan,         nan],
       [-1.11237618,         nan, -3.13514373]])

In [101]:
# 각 성분의 부호 계싼하기 (+는 1, -는 -1, 0인경우 0)
np.sign(arr1)

array([[ 1.,  1.,  1.],
       [ 1.,  1., -1.],
       [ 1., -1.,  1.],
       [ 1., -1., -1.],
       [ 1., -1.,  1.]])

In [102]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기
np.ceil(arr1)

array([[ 2.,  1.,  1.],
       [ 1.,  3., -0.],
       [ 1., -0.,  2.],
       [ 2., -1., -0.],
       [ 1., -0.,  1.]])

In [103]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기
np.floor(arr1)

array([[ 1.,  0.,  0.],
       [ 0.,  2., -1.],
       [ 0., -1.,  1.],
       [ 1., -2., -1.],
       [ 0., -1.,  0.]])

In [104]:
# 각 성분이 NaN인 경우 True를 아닌 경우, False를 반환.
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [105]:
np.isnan(np.log(arr1))

C:\Users\ai9198\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[False, False, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True,  True],
       [False,  True, False]])

In [108]:
#각 성분이 무한대인 경우 True, 아닌경우 false를 반환.
np.isinf(arr1)
np.isinf(np.log(arr1))

C:\Users\ai9198\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [109]:
# 각 성분에 대해 삼각함수 값을 계산하기 (cos, cosh, sin, sinh, tan, tanh)
np.cos(arr1)

array([[ 0.28167784,  0.99992984,  0.81914729],
       [ 0.92933806, -0.95828412,  0.93248685],
       [ 0.9678774 ,  0.87770273, -0.26629237],
       [-0.20043294, -0.21130564,  0.94292553],
       [ 0.89492573,  0.89196034,  0.99352922]])

In [110]:
np.tan(arr1)

array([[ 3.40640586,  0.01184629,  0.7002199 ],
       [ 0.39730426, -0.29825949, -0.38735553],
       [ 0.25976701, -0.54597701, -3.61967674],
       [-4.88795624,  4.625622  , -0.3531601 ],
       [ 0.49860576, -0.50687639,  0.11431649]])

### 6-2. 두개의 array에 적용되는 함수

In [114]:
arr1

array([[ 1.28525402,  0.01184574,  0.61087353],
       [ 0.3781803 ,  2.85173342, -0.36955867],
       [ 0.25414981, -0.4997493 ,  1.84034079],
       [ 1.77259613, -1.7837069 , -0.33948728],
       [ 0.4625316 , -0.46913358,  0.11382239]])

In [116]:
arr2 = np.random.randn(5,3)
arr2

array([[-1.41306567,  1.22115643, -0.4197584 ],
       [-0.15800435,  0.55463765, -0.78753348],
       [-1.15431173,  0.36672464,  0.18208554],
       [ 0.00143837, -0.81076103,  0.33319283],
       [-0.91955173,  0.03513652, -1.43464068]])

In [117]:
# 두개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기
# (add, subtract, multiply, divide)


In [118]:
np.multiply(arr1, arr2)

array([[-1.81614833,  0.0144655 , -0.25641929],
       [-0.05975413,  1.58167871,  0.29103983],
       [-0.2933681 , -0.18327038,  0.33509944],
       [ 0.00254965,  1.44616005, -0.11311473],
       [-0.42532173, -0.01648372, -0.16329423]])

In [119]:
arr1 * arr2

array([[-1.81614833,  0.0144655 , -0.25641929],
       [-0.05975413,  1.58167871,  0.29103983],
       [-0.2933681 , -0.18327038,  0.33509944],
       [ 0.00254965,  1.44616005, -0.11311473],
       [-0.42532173, -0.01648372, -0.16329423]])

In [120]:
# 두개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 만 가져옴.
# maximum, minimum
np.maximum(arr1, arr2)

array([[ 1.28525402,  1.22115643,  0.61087353],
       [ 0.3781803 ,  2.85173342, -0.36955867],
       [ 0.25414981,  0.36672464,  1.84034079],
       [ 1.77259613, -0.81076103,  0.33319283],
       [ 0.4625316 ,  0.03513652,  0.11382239]])

### 6-3 통계함수
통계 함수를 통해 array의 합이나 평균등을 구할 때, 
추가로 axis라는 인자에 대한 값을 지정하여 열 또는 행의 합 또는 평균등을 구할 수 있다.


In [127]:
arr1 = np.array([[1,2,3,4],[0,1,0,1],[1,2,3,4]])
arr1

array([[1, 2, 3, 4],
       [0, 1, 0, 1],
       [1, 2, 3, 4]])

In [128]:
# 전체 성분의 합을 계싼
np.sum(arr1)

22

In [129]:
# 각 행의 모든 요소를 합
np.sum(arr1, axis=1)

array([10,  2, 10])

In [131]:
# 열 간의 합
np.sum(arr1, axis=0)

array([2, 5, 6, 9])

In [132]:
# 전체 성분의 평균을 계산
np.mean(arr1)

1.8333333333333333

In [134]:
# 각 열의 평균을 계산
np.mean(arr1, axis=0)

array([0.66666667, 1.66666667, 2.        , 3.        ])

In [135]:
# 각 행의 평균
np.mean(arr1, axis=1)

array([2.5, 0.5, 2.5])

In [137]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 (std, var, min, max)
np.std(arr1)

array([1, 0, 1])

In [139]:
np.min(arr1, axis=1)

array([1, 0, 1])

In [140]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환. (argmin, argmax)
np.argmin(arr1)

4

In [141]:
np.argmax(arr1, axis=0)

array([0, 0, 0, 0], dtype=int64)

In [142]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산(cumsum, cumprod)
np.cumsum(arr1)

array([ 1,  3,  6, 10, 10, 11, 11, 12, 13, 15, 18, 22], dtype=int32)

In [143]:
np.cumprod(arr1)

array([ 1,  2,  6, 24,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int32)

### 6-4 기타함수

In [145]:
arr1

array([[1, 2, 3, 4],
       [0, 1, 0, 1],
       [1, 2, 3, 4]])

In [146]:
# 각 행별 오름차순 정렬
np.sort(arr1)

array([[1, 2, 3, 4],
       [0, 0, 1, 1],
       [1, 2, 3, 4]])

In [149]:
# 전체 요소 오름차순 정렬
np.sort(arr1)[::-1]

array([[1, 2, 3, 4],
       [0, 0, 1, 1],
       [1, 2, 3, 4]])

In [150]:
# 행 방향으로 오름차순으로 정렬
np.sort(arr1,axis=0)

array([[0, 1, 0, 1],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])